---
# roles/jitsi/meta/main.yml

galaxy_info:
  role_name: jitsi
  author: it-stack-dev
  description: Deploy Jitsi Meet video conferencing server
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - jitsi
    - video
    - conferencing
    - it-stack

dependencies:
  - role: common