---
# roles/glpi/meta/main.yml

galaxy_info:
  role_name: glpi
  author: it-stack-dev
  description: Deploy GLPI IT service management platform
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - glpi
    - itsm
    - servicedesk
    - it-stack

dependencies:
  - role: common