---
galaxy_info:
  role_name: postgresql
  author: it-stack-dev
  description: Deploy and configure PostgreSQL 16 with all IT-Stack service databases
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - database
    - postgresql
    - sql

dependencies:
  - role: common
