---
# roles/graylog/handlers/main.yml

- name: "restart graylog-server"
  ansible.builtin.systemd:
    name: graylog-server
    state: restarted

- name: "reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true