---
# roles/traefik/handlers/main.yml

- name: restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload ufw
  community.general.ufw:
    state: enabled
